repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: check-ast
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        language_version: python3.10.12
        args: [--max-line-length=120]
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: v1.6.0
#     hooks:
#     -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
        args: [--py39-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
    -   id: add-trailing-comma
# -   repo: https://github.com/asottile/setup-cfg-fmt
#     rev: v1.20.0
#     hooks:
#     -   id: setup-cfg-fmt
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake
        args: [--in-place, --remove-all-unused-imports]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.2.0
#     hooks:
#     -   id: mypy
#         args: [--ignore-missing-imports, --disallow-untyped-defs, --disallow-any-generics]
#         # args: [
#         #     --check-untyped-defs,
#         #     --disallow-any-generics,
#         #     --disallow-incomplete-defs,
#         #     --disallow-untyped-defs,
#         #     --no-implicit-optional,
#         #     --ignore-missing-imports
#         # ]
#         additional_dependencies: [types-all]
-   repo: https://github.com/rstcheck/rstcheck
    rev: v6.1.2
    hooks:
    -   id: rstcheck
